### ISSUE TITLE
No ScSS complier

### ISSUE THREAD

**Issue by jeanpaulpitman** [cp3402-students/cp3402-2021-site-cp3402-2021-team08#10]
I have lost the ability to contribute with the move to Scss. 
I have no way of checking my styles. 
I have tried setting up, Gurnt and GUlP, and built-in watcher in PHP Storm. nothing is working.

**Comment by Keegan-Cruickshank** [comment]
What errors does the watch method give in php storm?

**Comment by Keegan-Cruickshank** [comment]
I appears changing to a simpler IDE fixed your issue. This is not a fix but a workaround given the current timeframe.
